### ISSUE TITLE
maybe some explanation about what `archive` does

### ISSUE THREAD

**Issue by yuriaps** [zimfw/archive#6]
### Is your feature request related to a problem? Please describe.

Hello guys, I'm new to lots of things about Unix
When I first looked at this module I thought it was about compressing but with the name archive.
So I started playing and it took me to a website that apparently archives files on a web database. I haven't read the about on this website, but I'd suggest a bit of explanation about what `archive` is, this may help beginners to want to install it.

**[EDIT]** Its late in the night I tried the archive in a new environment and it work good, I need to test, but I'm almost pretty sure is that the plugin `web-search` of **ohmyzsh is in conflict** with `archive`. I will do more tests tomorrow to open a bug

### Describe the solution you'd like

~~Some tl;dr on this page, or some `--help` on the command~~

### Describe alternatives you've considered

~~A hyperlink to the website of archive where explains how it works~~

**Comment by yuriaps** [comment]
What do you think about changing this line:
archive generates an archive based on file extension. Syntax is `archive myarchive.tar.gz /path/to/be/archived`

to: Syntax is `archive myarchive.<choosen_extension> /path/to/be/archived`

**Comment by ericbn** [comment]
Hi @yuriaps.

Regarding "it took me to a website that apparently archives files on a web database", this is not the intention of this module.

I see the web-search plugin from ohmyzsh defines an archive alias:

https://github.com/ohmyzsh/ohmyzsh/blob/b81915d3293cc4657cec64202b9fd991b96b4ba2/plugins/web-search/web-search.plugin.zsh#L66

so this will conflict with the archive function defined here.

Regarding adding the usage to the documentation, besides the examples, I can work on that.
